### ISSUE TITLE
Type Inference for fastfamily causes error

### ISSUE THREAD

**Issue by Jarrio** [Aidan63/ecs#4]
`@:fastFamily var data = {id:String, info:Foo<Array<Float>>}`
> Error: Expected expression

A workaround is to create a typedef `typedef PreTyped = Foo<CandleHolder<Array<Float>>`

**Comment by Aidan63** [comment]
Hmm, seems that this is a limit of macros when using anonymous object creation. Did some initial tests and it seems possible if I change the family syntax to `@:fastFamily var data : { id : String, info : Foo<Array<Type>> }` ( : instead of =). I'll see about updating it tomorrow.

**Comment by Aidan63** [comment]
Turnt out to be a bit more work than expected, but worth it in the end I think. You can now use types with parameters like `Array<String>` for components and resources. The family definition sytax now uses type hints instead of object assignment, so you'll need to go through all your systems and change the `var fam = { ... }` to `var fam : { ... }`.

**Comment by Jarrio** [comment]
Neat change! Thanks a lot :D
